#!/usr/bin/env bash
# Script that install nginx on Ubuntu machine
#Configure your Nginx server so that /redirect_me is redirecting to another page

sudo apt-get -y update
sudo apt-get -y install nginx

echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

sudo sed -i "s/server_name _;\n\trewrite ^\/direct_me https://www.youtube.com/channel/UCOGuCTcfkhxVZSSPyC-Iq1A permanent;/" /etc/nginx/sites-enabled/default

sudo service nginx start
