#!/usr/bin/env bash
# Install NGINX server, set mensaje and redirection the server

apt-get -y update
apt-get -y install nginx

echo "Hello World!" | sudo dd status=none of=/var/www/html/index.html

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null

NEW_RULE="\\\n\tlocation /redirect_me {\n\t\t return 301 https://www.youtube.com/channel/UCOGuCTcfkhxVZSSPyC-Iq1A;\n\t}\n"

sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.backup

sudo sed -i "53i $NEW_RULE" /etc/nginx/sites-available/default

NEW_RULE="\\\n\terror_page 404 /404.html;\n\n\tlocation = /404.html {\n\t\tinternal;\n\t}\n"

sudo sed -i "53i $NEW_RULE" /etc/nginx/sites-available/default

sudo service nginx restart
