#!/usr/bin/env bash
# Install and configure HAProxy load balancer

sudo apt-get -y update
sudo apt-get install -y haproxy

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend silverbanks.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 85367-web-01 54.210.142.210:80
        server 85367-web-02 54.165.19.82:80
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
service haproxy restart
