#!/usr/bin/env bash
# configures an Ubuntu server with the details below:
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8./usr/bin/env bash
# The checker is running on Docker

cp /etc/hosts ~/hosts.new
echo "127.0.0.2		localhost" > ~/hosts.new
echo "8.8.8.8		facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
